### ISSUE TITLE
Parameter Problem

### ISSUE THREAD

**Issue by yyhyyhyyhyyh** [kookie12/FlexiEdit#2]
Hi. This is a nice work!
I have some questions about the parameters
What is the function of the blended_word parameter?

**Comment by kookie12** [comment]
Hi, @yyhyyhyyhyyh. Thank you for your interest in our work!

The `blended_word` parameter refers to the object(s) to be edited in both the `source_prompt` and `target_prompt`.
In our code, we have two versions: FlexiEdit and the advanced version. The blended_word is utilized exclusively in the advanced version. This approach allows us to input the subject of the edit target as `blended_word`, which helps identify the background area of the subject. The background, excluding the specified object, is then stored as an activation map. This process significantly enhances the background preservation performance during the editing process.

**Comment by yyhyyhyyhyyh** [comment]
Thanks for your reply！
